### ISSUE TITLE
Are any pretrained models available?

### ISSUE THREAD

**Issue by armheb** [minar09/cp-vton-plus#1]
Hi, Great work, and thanks for sharing. I wanted to test your model, are there any pretrained weights available?

**Comment by minar09** [comment]
Hi @armheb , thanks for your kind words. Yes, pretrained models are available. Please visit this link to download: https://1drv.ms/u/s!Ai8t8GAHdzVUiQA-o3C7cnrfGN6O?e=gUZQI6 
Thank you!

**Comment by armheb** [comment]
Great! Thank you so much for sharing.
