### ISSUE TITLE
some issue with segmented mask in dataset_neck_skin_correction.py

### ISSUE THREAD

**Issue by sumit-pundir** [minar09/cp-vton-plus#12]
When I run dataset_neck_skin_correction.py on the train data I'm getting the following error.
![Screen Shot 2020-08-09 at 7 33 32 PM](https://user-images.githubusercontent.com/69425423/89734078-67767000-da77-11ea-9bf8-731e74490021.png)

Is it due to image parsing since I'm using https://github.com/Engineering-Course/LIP_JPPNet for parsing ?

**Comment by minar09** [comment]
Hi @sumit-pundir , I think you can simply convert your segmentation files into Grayscale from RGB, either using opencv or pillow.

**Comment by sumitpundir24** [comment]
Solved. Thanks @minar09 for quick reply.

**Comment by minar09** [comment]
Closing the issue as its resolved. Feel free to reopen in case there are still problems.
