### ISSUE TITLE
A question about your workshop slide page 11

### ISSUE THREAD

**Issue by LuoWeihao95** [minar09/cp-vton-plus#13]
In your [slide](https://minar09.github.io/cpvtonplus/CVPRW20_CPVTONPLUS_SLIDE.pdf) , page 11, cp-vton result and your result have difference in shoulders of the cloth, but the input of upper region is the same, why does it happen?

**Comment by thaithanhtuan** [comment]
If you check page 8 in the slide, 
![image](https://user-images.githubusercontent.com/19486377/89879552-180e7c00-dbfe-11ea-9f0d-ce0406a8955b.png)
This was made by changing body shape to the input of the network.

**Comment by LuoWeihao95** [comment]
> If you check page 8 in the slide,
> ![image](https://user-images.githubusercontent.com/19486377/89879552-180e7c00-dbfe-11ea-9f0d-ce0406a8955b.png)
> This was made by changing body shape to the input of the network.

Oh...Sorry, I forget this. I get it now. Thanks very much.

By the way, Will you release the code about your another workshop 3D Reconstruction of Clothes using a Human Body Model and its Application to Image-based Virtual Try-On? I'm very interested in it.

**Comment by thaithanhtuan** [comment]
> By the way, Will you release the code about your another workshop 3D Reconstruction of Clothes using a Human Body Model and its Application to Image-based Virtual Try-On? I'm very interested in it.

Sorry. At the moment, we can not release the code.

**Comment by LuoWeihao95** [comment]
> > By the way, Will you release the code about your another workshop 3D Reconstruction of Clothes using a Human Body Model and its Application to Image-based Virtual Try-On? I'm very interested in it.
> 
> Sorry. At the moment, we can not release the code.

Ok, Thanks for your reply.
