### ISSUE TITLE
Cannot untar the dataset with download.py

### ISSUE THREAD

**Issue by ItsJasonPan** [minar09/cp-vton-plus#16]
<img width="726" alt="image" src="https://user-images.githubusercontent.com/43100398/90727684-aa172400-e291-11ea-9c13-d562ec3f9431.png">

I encountered the same problem as shown above on both MacOS and Linux. I also tried downloading the dataset manually from the google drive but I still couldn't untar it.

**Comment by thaithanhtuan** [comment]
This data is from CPVTON implementation: https://github.com/sergeywong/cp-vton
From the Error message, it may come from the downloaded file is not successful? It should be 228 MB.
Can you check to download data from CPVTON github given in google drive.

**Comment by minar09** [comment]
Hi @ItsJasonPan , the whole dataset is uploaded in onedrive (link: https://1drv.ms/u/s!Ai8t8GAHdzVUiQSYB-bD016tTFjQ). This contains full and processed dataset, which you can test directly with the pre-trained models. No need to run dataset_neck_skin_correction or body_binary_mask. Hope that helps. Thank you.

**Comment by ItsJasonPan** [comment]
Thanks @minar09 @thaithanhtuan , it seems that the original dataset is corrupted or incompatible with macOS.
