### ISSUE TITLE
testing gmm network gave cublas runtime error

### ISSUE THREAD

**Issue by koushiksura** [minar09/cp-vton-plus#17]
testing gmm network gave this error

python3 test.py --name GMM --stage GMM --workers 4 --datamode test --data_list test_pairs.txt --checkpoint checkpoints/GMM/gmm_final.pth

Namespace(batch_size=4, checkpoint='checkpoints/GMM/gmm_final.pth', data_list='test_pairs.txt', datamode='test', dataroot='data', display_count=1, fine_height=256, fine_width=192, gpu_ids='', grid_size=5, name='GMM', radius=5, result_dir='result', shuffle=False, stage='GMM', tensorboard_dir='tensorboard', workers=4)
Start to test stage: GMM, named: GMM!
initialization method [normal]
initialization method [normal]
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
Traceback (most recent call last):
  File "test.py", line 225, in <module>
    main()
  File "test.py", line 211, in main
    test_gmm(opt, test_loader, model, board)
  File "test.py", line 99, in test_gmm
    grid, theta = model(agnostic, cm)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Desktop/cpvtonplus/cp-vton-plus-master/networks.py", line 522, in forward
    correlation = self.correlation(featureA, featureB)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Desktop/cpvtonplus/cp-vton-plus-master/networks.py", line 103, in forward
    feature_mul = torch.bmm(feature_B, feature_A)
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:411

**Comment by minar09** [comment]
Hi @koushiksura , you have `gpu_ids=''` in your run command argument. I think you need to select a GPU id to run the program.

**Comment by koushiksura** [comment]
> Hi @koushiksura , you have `gpu_ids=''` in your run command argument. I think you need to select a GPU id to run the program.

I tried, Still facing same issue @minar09

**Comment by koushiksura** [comment]
could you please help me with python, cuda and cudnn versions

**Comment by minar09** [comment]
@koushiksura , can you please check your pytorch version also. We tested the model in python 3, pytorch 0.4.1, torchvision 0.2.1,
with gpu id argument e.g. `gpu_ids='0'`. cuda/cudnn version is prolly 10/10.2

**Comment by koushiksura** [comment]
Working after re installing pytorch from source whl.
Thanks...
