### ISSUE TITLE
Size mismatch error while running test.py for GMM model

### ISSUE THREAD

**Issue by Akhileshkakade** [minar09/cp-vton-plus#2]
Hey, I am trying to execute the test.py for GMM as mentioned in the repo it is giving the size mismatch error.

RuntimeError: Error(s) in loading state_dict for GMM:
        size mismatch for extractionB.model.0.weight: copying a param of torch.Size([64, 3, 4, 4]) from checkpoint, where the shape is torch.Size([64, 1, 4, 4]) in current model.

Kindly help me with this.

**Comment by minar09** [comment]
Hi @Akhileshkakade , thank you very much for pointing out the mistake. I updated the repo now. Please try again with the updated code. Thank you.

**Comment by Akhileshkakade** [comment]
Yeah sure.

**Comment by minar09** [comment]
If your issue is solved, I think we can close the issue. Thanks.

**Comment by Akhileshkakade** [comment]
I will try it today and let you know.

**Comment by minar09** [comment]
Wrong segmentation and try-on results issues are solved here: https://github.com/minar09/cp-vton-plus/issues/8#issuecomment-667022408 #8

**Comment by minar09** [comment]
Closing the issue as its resolved. Feel free to reopen in case there are still problems.
