### ISSUE TITLE
Restart training from checkpoint

### ISSUE THREAD

**Issue by Bouncer51** [minar09/cp-vton-plus#20]
Hi, there is a way to restart the training from a specific checkpoint?
I'm trying this command but it starts always from step 0
python train.py
--stage GMM
--workers 8
--save_count 500
--checkpoint "checkpoints/gmm_train_new/step_000500.pth"

**Comment by thaithanhtuan** [comment]
> Hi, there is a way to restart the training from a specific checkpoint?
> I'm trying this command but it starts always from step 0
> python train.py
> --stage GMM
> --workers 8
> --save_count 500
> --checkpoint "checkpoints/gmm_train_new/step_000500.pth"

If you do so, It actually continues to train from step 500, but if you want the output print from 500 (not step 0), from train.py line 70, you can change from:
`for step in range(opt.keep_step + opt.decay_step):`
to
`start_step = 500
for step in range(start_step, opt.keep_step + opt.decay_step):`
