### ISSUE TITLE
CPU version

### ISSUE THREAD

**Issue by Bouncer51** [minar09/cp-vton-plus#21]
Does this model work on cpu version while testing/inference. 
if yes,
please tell me changes I would have to make.

Thanks

**Comment by minar09** [comment]
Hi @Bouncer51 , were you able to run in CPU? It would be helpful for others if you provide some details on how you did it. Thanks.

**Comment by Bouncer51** [comment]
yea, i was able to run on cpu version, wherever there was  .cuda() in code i removed it and i commented lines model.cuda(). it worked fine for testing 1 image on cpu results were same as gpu version.
