### ISSUE TITLE
Blue Hue & Blurriness

### ISSUE THREAD

**Issue by frankiesquared** [minar09/cp-vton-plus#30]
This is great work!

How do I get rid of the blue hue and blurriness?

![image](https://user-images.githubusercontent.com/59422631/97167183-9b426700-1743-11eb-9deb-2ccf9f264f5d.png)

**Comment by minar09** [comment]
Did you change something in the code or data? Otherwise, this should not be expected.

**Comment by thaithanhtuan** [comment]
It looks like you got the wrong input to the network, you can debug and check the cp_dataset.py :: getItem(). (Did you forget to normalize the input image).
Or, at the step for combination and visualization on test.py.

**Comment by frankiesquared** [comment]
Thanks. It was the normalization.
