### ISSUE TITLE
 train does not start

### ISSUE THREAD

**Issue by ikenaga530** [minar09/cp-vton-plus#34]
I get the following error.
I would like to know what the solution is.

![Screenshot from 2020-11-02 23-05-55](https://user-images.githubusercontent.com/68841019/97877073-056c9480-1d60-11eb-8220-de68bc65e493.png)

**Comment by thaithanhtuan** [comment]
Look like something wrong with your GPU. To run the code you need at least one GPU (NVIDIA).
To run the code without GPU, you should modify the code. Any place you see:
`.cuda() `
change it to
`.cpu()`
Regards.
