### ISSUE TITLE
generate pose

### ISSUE THREAD

**Issue by dnalexen** [minar09/cp-vton-plus#38]
Hello, is it possible to have the code that you used to generate the pose keypoints? I try to generate the keypoints of some image of the cp-vton+ with the code on this github repository: https://github.com/minar09/openpose-pytorch. However, I do not find the same points as the ones in the cp-viton+ dataset.

**Comment by minar09** [comment]
https://github.com/minar09/cp-vton-plus/blob/master/README.md#testing-with-custom-images

**Comment by JahangirButt-BU** [comment]
@minar09 which version of openpose should i use to genenrate the keypoints?

**Comment by minar09** [comment]
@JahangirButt-BU , you can use any version from the official openpose, just be sure to generate with COCO-18 model.

**Comment by JahangirButt-BU** [comment]
@minar09 yes i did generte json file using coco-18 model but in the latest version they change the output json file format

json file using openpose 1.7.0: https://pastebin.com/jrLBEVG9

**Comment by minar09** [comment]
I think it will be okay if you just change "pose_keypoints" in the cp_dataset.py into "pose_keypoints_2d".

**Comment by JahangirButt-BU** [comment]
@minar09  Thankyou very much its works..

**Comment by echoi3** [comment]
Could you let me know what command(s) did you use to generate 18 key points from coco-18 model? I keep getting 25 key points, which seems to be set as a default, and can't change the command to generate 18 points.

**Comment by JahangirButt-BU** [comment]
"#./build/examples/openpose/openpose.bin --image_dir /home/fyp/Desktop/Try_On#4/data/test/image --model_pose COCO --write_json /home/fyp/Desktop/Try_On#4/data/test/pose"

i used this command to generate the required points
