### ISSUE TITLE
TOM model testing error

### ISSUE THREAD

**Issue by Naman97** [minar09/cp-vton-plus#4]
When executing the test.py script for TOM model, FileNotFoundError appears. 
Line number 56 inside __getitem__ method of cp_dataset.py is causing the error because there is no directory present as such named data/test/warp-cloth.

**Comment by minar09** [comment]
Hi, @Naman97 , to test the TOM model, you need to run test.py for GMM model first. GMM model will generate results in "warp-cloth" and "warp-mask" folders inside the result folder. After that, you need to copy "warp-cloth" and "warp-mask" folders to your data directory, for example inside "data/test/" folder for testing. Then, you can run TOM model to test the try-on output using the warped clothes output from GMM. Hope that helps. Thanks.
