### ISSUE TITLE
custom image error

### ISSUE THREAD

**Issue by ikenaga530** [minar09/cp-vton-plus#40]
I'm going to try cp-vton-plus with custom images

In dataset_neck_skin_correction.py, only custom images get the following error

Traceback (most recent call last):
  File "dataset_neck_skin_correction.py", line 258, in <module>
    main()
  File "dataset_neck_skin_correction.py", line 254, in main
    image_dir, seg_dir, each[0], mask, updated_seg_dir)# def update_image_segmentation(data_dir, mask_dir, image_name, mask_name, save_dir=None, save_vis=True):
  File "dataset_neck_skin_correction.py", line 184, in update_image_segmentation
    result = segmentation + neck_mask
ValueError: operands could not be broadcast together with shapes (256,192,3) (256,192)

The dataset image succeeds, the custom image gives me this error. Do you know the cause?

**Comment by ikenaga530** [comment]
The custom image had a bit depth of 24 while the image in the dataset had a bit depth of 8.Image-parse generated using LIP_JPPNet.
So, I changed the bit depth to 8 and ran dataset_neck_skin_connection.py and it did not show any error, but the output result was different

<dataset images>
image
![000001_0](https://user-images.githubusercontent.com/68841019/100059182-fadc8100-2e6d-11eb-8ac9-18ace5016a6b.jpg)
image-parse
![000001_0](https://user-images.githubusercontent.com/68841019/100059203-04fe7f80-2e6e-11eb-978f-963e210bf815.png)
image-parse-new
![000001_0](https://user-images.githubusercontent.com/68841019/100059209-08920680-2e6e-11eb-83af-995ff4abb92f.png)
image-parse-new-vis
![000001_0_vis](https://user-images.githubuserconte
<custom image>
image
![019600_0](https://user-images.githubusercontent.com/68841019/100059291-25c6d500-2e6e-11eb-8ba5-d8f111dc09e7.jpg)
image-parse
![019600_0](https://user-images.githubusercontent.com/68841019/100059295-2cede300-2e6e-11eb-832e-bb7f01dc92fc.png)
image-parse-new
![019600_0](https://user-images.githubusercontent.com/68841019/100059314-337c5a80-2e6e-11eb-9c57-64963cbf3b3d.png)
image-parse-new-vis
![019600_0_vis](https://user-images.githubusercontent.com/68841019/100059336-39723b80-2e6e-11eb-99be-cac780318fd1.png)

**Comment by ikenaga530** [comment]
The custom image had a bit depth of 24 while the image in the dataset had a bit depth of 8.Image-parse generated using LIP_JPPNet.
So, I changed the bit depth to 8 and ran dataset_neck_skin_connection.py and it did not show any error, but the output result was different

image
![019600_0](https://user-images.githubusercontent.com/68841019/100059611-b3a2c000-2e6e-11eb-8404-268f97e69fff.jpg)

image-parse
![019600_0](https://user-images.githubusercontent.com/68841019/100059628-bdc4be80-2e6e-11eb-8123-47412f9e5e50.png)

image-parse-new
![019600_0](https://user-images.githubusercontent.com/68841019/100059651-c4ebcc80-2e6e-11eb-8ced-ecff5efcf310.png)

image-parse-new-vis
![019600_0_vis](https://user-images.githubusercontent.com/68841019/100059682-cfa66180-2e6e-11eb-8bd2-f595257c7bb0.png)

Image-parse is what changed to a bit depth of 8

Why is the cause? Best regards

**Comment by huangpen** [comment]
Can you show me which line of code needs to be changed in order to generate 8 bit-depth image? Is it like this?
`    # Load the segmentation in grayscale and make binary mask
    segmentation = Image.open(seg_pth).convert('L')`

**Comment by minar09** [comment]
When you are using segmentation for training/testing, please use the grayscale file always - 
![image](https://user-images.githubusercontent.com/3684134/101793880-9d248600-3b49-11eb-8e02-eb196d5144b9.png)

RGB/colored one is only for visualization, this one is creating much confusion I guess.
Also, you don't need to run LIP_JPPNet + dataset_neck_skin_correction.py combination, if you generate segmentation using only CIHP_PGN or Graphonomy. Hope that helps. Thanks!
@ikenaga530 @huangpen
