### ISSUE TITLE
RuntimeError: output with shape [1, 256, 192] doesn't match the broadcast shape [3, 256, 192]

### ISSUE THREAD

**Issue by 1702609** [minar09/cp-vton-plus#48]
I have been following the tutorial and I am unable to train the algorithm. I have downloaded the dataset via data_download.py. What should I do?

**Comment by minar09** [comment]
Hi @1702609 , the repository and the readme is updated. Please try again with the updated instructions and code from the start. Thanks.

**Comment by 1702609** [comment]
> Hi @1702609 , the repository and the readme is updated. Please try again with the updated instructions and code from the start. Thanks.

I have pulled the latest repository and still getting the same issue. Specifically, the problem occurs in the cp_dataset.py line 139 'shape_ori = self.transform(parse_shape_ori)'. Have you got any more suggestions?

**Comment by minar09** [comment]
Can you please provide more details on the error?
Also, you can download the dataset from our download link, not through the data_download.py.

**Comment by 1702609** [comment]
There was a problem with my python environment. I fixed it. Thanks

**Comment by ISL270** [comment]
> There was a problem with my python environment. I fixed it. Thanks

how did you fix it please

**Comment by Vishvesh8** [comment]
> > There was a problem with my python environment. I fixed it. Thanks
> 
> how did you fix it please

I switched from Python 2.7 to Python 3.7 thats all
