### ISSUE TITLE
CIHP_PGN model unusable due to Python 2.7 depreciation

### ISSUE THREAD

**Issue by pra17dod** [minar09/cp-vton-plus#53]
While custom image testing, the CIHP_PGN model for the image-parse is not working after the depreciation of the Python 2.7. Could you please suggest any other model for the same or any workaround for working implementation in Python 3 other than default python 2 to 3 converters?

**Comment by minar09** [comment]
Hi, I have a working CIHP_PGN repository in python 3, you could check if you like to: https://github.com/minar09/PGN_tf .
However, I think you can use CIHP_PGN (https://github.com/Engineering-Course/CIHP_PGN) or Graphonomy (https://github.com/Gaoyiminggithub/Graphonomy) either of the models for generating segmentation, and their official codebase should be or work in python 3 AFAIK.

**Comment by pra17dod** [comment]
I am very grateful for your reply, your work on [PGN_tf](https://github.com/minar09/PGN_tf) really helped.
