### ISSUE TITLE
Wrong output image while testing

### ISSUE THREAD

**Issue by aeg12345** [minar09/cp-vton-plus#57]
Greetings,
When I try to generate images using the sample dataset but changing the image pairs I still get the same image outputs from the test dataset.
I wanted to test this before trying out custom image.

pip env:
home = /usr/local/bin
include-system-site-packages = false
version = 3.6.12

requirements.txt:
torch==0.4.1
#torchvision
torchvision==0.2.1
tensorboardX
pillow
numpy
opencv-contrib-python

Sample Test pairs:
000001_0.jpg 019552_1.jpg
000010_0.jpg 004387_1.jpg
000020_0.jpg 019552_1.jpg

Result Dir outputs:
![000001_0](https://user-images.githubusercontent.com/17311850/108604545-a048b780-73bf-11eb-93aa-82e5d1b75520.jpg)
![000010_0](https://user-images.githubusercontent.com/17311850/108604546-a179e480-73bf-11eb-9829-041b1d5c8258.jpg)
![000020_0](https://user-images.githubusercontent.com/17311850/108604547-a179e480-73bf-11eb-8b61-0bf346d37f4f.jpg)

Tryon outputs:

![000001_0](https://user-images.githubusercontent.com/17311850/108604558-b5254b00-73bf-11eb-9f70-54a1c3af612e.jpg)
![000010_0](https://user-images.githubusercontent.com/17311850/108604559-b5bde180-73bf-11eb-84c9-89efb77294a3.jpg)
![000020_0](https://user-images.githubusercontent.com/17311850/108604560-b5bde180-73bf-11eb-911a-4ea96dcc0ed0.jpg)

Sample clothes:
![019552_1](https://user-images.githubusercontent.com/17311850/108604576-dab25480-73bf-11eb-97d8-d2c74e8cd015.jpg)
![004387_1](https://user-images.githubusercontent.com/17311850/108604586-e867da00-73bf-11eb-8318-655e15ee983c.jpg)

The test pairs in the default test txt:
000001_0.jpg 001744_1.jpg

000010_0.jpg 004325_1.jpg
000020_0.jpg 002022_1.jpg

Test pair sample cloth images:
![001744_1](https://user-images.githubusercontent.com/17311850/108604618-11886a80-73c0-11eb-8ad0-d3b6c34f3c06.jpg)
![004325_1](https://user-images.githubusercontent.com/17311850/108604621-1b11d280-73c0-11eb-9ba9-d3fa0843679c.jpg)
![002022_1](https://user-images.githubusercontent.com/17311850/108604630-26fd9480-73c0-11eb-8336-46266bc835a4.jpg)

I have made no changes to test py, the commands I use to run are:

python3.6 test.py --name GMM --stage GMM --batch-size 1 --datamode test --data_list test_pairs_new.txt --checkpoint checkpoints/GMM/gmm_final.pth

python3.6 test.py --name TOM --stage TOM --batch-size 1 --datamode test --data_list test_pairs_new.txt --checkpoint checkpoints/TOM/tom_final.pth

[test_pairs_new.txt](https://github.com/minar09/cp-vton-plus/files/6015955/test_pairs_new.txt)

**Comment by muhammedsaid** [comment]
Please, read the Readme file
"Copy the "warp-cloth" and "warp-mask" folders into your data directory, for example inside "data/test" folder."

**Comment by aeg12345** [comment]
It was due to forgetting to move the generated GMM relevant folders to test folder.
