### ISSUE TITLE
Colab Demo?

### ISSUE THREAD

**Issue by Adeel-Intizar** [minar09/cp-vton-plus#59]
Hello, Thank you for your great work
It will be very helpful for everyone if you kindly provide a colab notebook demo for this amazing repo
It will resolve many issues and everyone can easily test it
Thank you, Looking forward to the demo

**Comment by minar09** [comment]
Hi @Adeel-Intizar , thanks for your interest. However, the authors are currently busy with other projects so a colab demo maybe not possible right now. However, you may find some colab demo from other users in the issues discussion section. Thanks for your understanding.
