### ISSUE TITLE
Why parse_head is not the same in GMM and TOM stage?

### ISSUE THREAD

**Issue by VVingerfly** [minar09/cp-vton-plus#62]
Hi, @minar09 @thaithanhtuan thanks for the great work!

I was wondering why `parse_head` is different in GMM and TOM stage, shouldn't they be the same?

https://github.com/minar09/cp-vton-plus/blob/916d7337703b49e18c8005f4b1847ba53c76c9e9/cp_dataset.py#L110-L124

B.R.

**Comment by minar09** [comment]
Hi @VVingerfly , actually that is one of the contributions of CP-VTON+. By using a different parse_head for GMM, we can preserve the original clothing shape around the neck. Please feel free to read the paper for more details. Thank you.

**Comment by VVingerfly** [comment]
Got it, thanks for your reply. Closing this issue now :-)
