### ISSUE TITLE
test with custom image：image shape

### ISSUE THREAD

**Issue by mcc1999** [minar09/cp-vton-plus#63]
I download the author's model, and want to test with my cunstom image. First, I run the GMM model to get  wrap-cloth, but I get the error as follow:
![image](https://user-images.githubusercontent.com/46415154/113398322-feaa8200-93d0-11eb-994e-4250a8cd2136.png)
The shape of im is (3, 256,192), and the pcm shape is (256,192, 3). When im * pcm, the error happened. 
After reshaping the pcm to (3,256,192),  I get another error as follow:
![image](https://user-images.githubusercontent.com/46415154/113398731-a1fb9700-93d1-11eb-855c-f7030829ecff.png)
I don't know where the wrong located, it's wrong with im shape? Or pcm shape? Or my custom image is in a wrong shape?
Should I reshape the im shape? @minar09

**Comment by minar09** [comment]
Hi @mcc1999 , sorry for the inconvenience. Please see this comment for the error details: https://github.com/minar09/cp-vton-plus/issues/60#issuecomment-817379874
