### ISSUE TITLE
How to generate cloth-mask

### ISSUE THREAD

**Issue by rafid08** [minar09/cp-vton-plus#66]
Following your instructions, I understood every concepts except the "Cloth Mask using opencv/pillow. Can you please give the reference of the instructions on generating cloth-mask? Thank you so much in advance!

**Comment by minar09** [comment]
Hi, @rafid08 , I have a separate repository for cloth-masking code: https://github.com/minar09/Clothing-Matching. You can try it or write a suitable program as per your needs.

**Comment by rafid08** [comment]
> 
> 
> Hi, @rafid08 , I have a separate repository for cloth-masking code: https://github.com/minar09/Clothing-Matching. You can try it or write a suitable program as per your needs.

Thank you so much!!!
