### ISSUE TITLE
output human face blurry ,any suggestions?

### ISSUE THREAD

**Issue by Apokar** [minar09/cp-vton-plus#70]
Thank you for the excellent work, I found the output clothes basically fit character but the characters' faces became blurry, any suggestions?

RESULT:
![1 (2)](https://user-images.githubusercontent.com/25199579/118607086-c3320e80-b7ea-11eb-8128-f756bec2f85b.jpg)

Here is data :

-- cloth
![3](https://user-images.githubusercontent.com/25199579/118606745-5880d300-b7ea-11eb-8320-6f77236b0411.jpg)

-- cloth-mask
![3](https://user-images.githubusercontent.com/25199579/118606884-8403bd80-b7ea-11eb-9a82-03381decf98f.jpg)

-- image
![1](https://user-images.githubusercontent.com/25199579/118606907-8bc36200-b7ea-11eb-97d7-4a040d85b9d0.jpg)

-- image-mask
![1](https://user-images.githubusercontent.com/25199579/118606917-8e25bc00-b7ea-11eb-8060-4924877e40a8.png)

-- image-parse
![1](https://user-images.githubusercontent.com/25199579/118606935-954cca00-b7ea-11eb-85a6-87dfaf2237c1.png)

-- image-parse-new
![1](https://user-images.githubusercontent.com/25199579/118606958-9b42ab00-b7ea-11eb-87f1-877604dd179a.png)

-- warp-cloth
![1](https://user-images.githubusercontent.com/25199579/118606975-9f6ec880-b7ea-11eb-884f-f48c375be417.jpg)

-- warp-mask
![1](https://user-images.githubusercontent.com/25199579/118606985-a39ae600-b7ea-11eb-9a74-e7f7ee0e9e18.jpg)

**Comment by minar09** [comment]
Hi @Apokar , are all of your output have blurry faces or just this? If it affects all, maybe you can debug the network more closely, looks like TOM network input is missing the im_head or something, not very sure though. Hope you can find it out. Good luck.

**Comment by Apokar** [comment]
> Hi @Apokar , are all of your output have blurry faces or just this? If it affects all, maybe you can debug the network more closely, looks like TOM network input is missing the im_head or something, not very sure though. Hope you can find it out. Good luck.


Haha,I misplaced the pictures in two folders.<image-parse><image-parse-new> 
Thx ur reply!

**Comment by omaraga12** [comment]
@Apokar can you explain how did you give solution to it? I have the same problem
![image](https://user-images.githubusercontent.com/64969223/146115592-7c80c11b-7193-4c34-b52f-3a0b92d28d57.png)
![image](https://user-images.githubusercontent.com/64969223/146115631-cc2750ed-e5d9-4db0-ac27-8d81821194c2.png)

**Comment by kukuhaza** [comment]
> 

I have face blurry problem too, how to solve this?
