### ISSUE TITLE
Creating image-mask

### ISSUE THREAD

**Issue by echoi3** [minar09/cp-vton-plus#74]
Could anyone help me with generating image-mask of person images? 

I was able to generate cloth-mask by looking into your [Cloth-Matching repo](https://github.com/minar09/Clothing-Matching), but I figured that generating image-mask is a bit different from generating cloth-mask.

Any help would be appreciated. 

Thanks in advance.

**Comment by minar09** [comment]
Hi @echoi3 , I hope you solved your issue by now. Sorry for my late response. You can convert the image-parse into binary masks by changing all the labels value >0 to 255, or you can use the masking code from that repo for the person image. You can utilize any suitable binary masking network pretrained model as well, e.g. deepcut etc.

**Comment by minar09** [comment]
You can also use the code from old commits: https://github.com/minar09/cp-vton-plus/blob/fcf29a512388881041ba84a97a43edfd1531cc38/body_binary_masking.py
