### ISSUE TITLE
Is there any code to generate person image-mask?

### ISSUE THREAD

**Issue by Sumukh0512** [minar09/cp-vton-plus#76]

**Comment by Sumukh0512** [comment]
@minar09 I am building an interface for the cp-viton plus based virtual try-on project and I need code for generating image-mask. Can you guide me?

**Comment by minar09** [comment]
@Sumukh0512, you can make image-mask by converting the image-parse into binary masks, or you can make use of the masking code from here: https://github.com/minar09/Clothing-Matching

**Comment by Sumukh0512** [comment]
@minar09  x-special/nautilus-clipboard
copy
recent:///ebc7354d2853ba326174e47d60d71b6e
I am giving image-parse as input for cloth_masking_thresholding.py . How am I supposed to get the image-mask? I need your help.

**Comment by Sumukh0512** [comment]
![Screenshot from 2021-06-26 17-56-08](https://user-images.githubusercontent.com/31795364/123512933-cea90d00-d6a7-11eb-9dc1-e795a12104e4.png)
This is the output . Why is it completely white? Same code I am able to get output for cloth-mask but not for image-mask should I make any changes to the code?

**Comment by minar09** [comment]
@Sumukh0512 , you can use the body_binary_masking.py from old commits (https://github.com/minar09/cp-vton-plus/blob/fcf29a512388881041ba84a97a43edfd1531cc38/body_binary_masking.py), although I removed it from current commits as it was making confusions. Thanks.

**Comment by Sumukh0512** [comment]
@minar09 thanks
