### ISSUE TITLE
How to obtain parse_hand ?

### ISSUE THREAD

**Issue by roy-sr** [minar09/cp-vton-plus#78]
Hi,

Is there any way to get the hand segmentation (not full arms)  of a model for all type of clothing (full sleeves, half sleeves, short sleeves or no sleeves)  ?

Cheers
Srijan

**Comment by minar09** [comment]
Hi @roy-sr , I am not sure what you mean. If you want to detect the hand (skin) segmentation, I think there are already separate segmentation labels defined for hands/legs. If you need the clothing sleeves detection, either you may need to build a separate model, or you may do some kind of image processing utilizing the human parsing and pose key points. Thanks.
