### ISSUE TITLE
can u explain this piece of code

### ISSUE THREAD

**Issue by gamenerd457** [minar09/cp-vton-plus#79]
parse_shape = (mask_array > 0).astype(np.float32)

        if self.stage == 'GMM':
            parse_head = (parse_array == 1).astype(np.float32) + \
                (parse_array == 4).astype(np.float32) + \
                (parse_array == 13).astype(
                    np.float32)  # CP-VTON+ GMM input (reserved regions)

**Comment by minar09** [comment]
@gamenerd457 , here's actually the head/face area labels are considered as in the human representation that is helpful for target clothing deformation. Please see the paper for more details.

**Comment by minar09** [comment]
@gamenerd457 , this is for drawing the heatmap image from the pose keypoints.
