### ISSUE TITLE
Bad results

### ISSUE THREAD

**Issue by vladvdovin27** [minar09/cp-vton-plus#87]
I have very strange results, can anyone tell me why this might be happening? Maybe I'm doing something wrong?
![img](https://user-images.githubusercontent.com/60712606/160287270-cd984151-7af7-4abe-8487-8e8b8add7f4c.jpg)

**Comment by Fafa87** [comment]
![image](https://user-images.githubusercontent.com/9865688/161355780-22e9a279-686d-424c-ad7e-3b6b7e6caf26.png)
:P

**Comment by minar09** [comment]
https://github.com/minar09/cp-vton-plus#what-to-do-in-case-of-unexpected-results

**Comment by vladvdovin27** [comment]
Thanks
