### ISSUE TITLE
GPU for inference

### ISSUE THREAD

**Issue by AnjaliSinghTW** [minar09/cp-vton-plus#88]
Is GPU mandatory for inference? If not, can you provide us instructions to do inference on CPU?

**Comment by vinodbukya6** [comment]
Hi, you can check my GitHub repo: https://github.com/vinodbukya6/cp-VTryon-plus-Flask-App

or you can replace .cuda() with .cpu() in test.py, networks.py

**Comment by AnjaliSinghTW** [comment]
Hi,
Thank you for your reply. I will do as you suggested.
Regards
