### ISSUE TITLE
Dataset invalidation

### ISSUE THREAD

**Issue by hbwanghang** [minar09/cp-vton-plus#93]
When reproducing the project, I found that the provided dataset URL has expired, can you provide it again？Thanks

**Comment by xiangyu-getklothed** [comment]
> When reproducing the project, I found that the provided dataset URL has expired, can you provide it again？Thanks

It's because the original dataset is no longer publicly available https://github.com/xthan/VITON#dataset

**Comment by minar09** [comment]
@hbwanghang, please check now.
